# Generated by Django 5.0.6 on 2024-06-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("logo", models.CharField(blank=True, max_length=150, null=True)),
                ("website", models.CharField(blank=True, max_length=150, null=True)),
                ("hidden", models.BooleanField(default=False)),
            ],
        ),
    ]
