# Generated by Django 5.0.6 on 2024-05-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_todo_star"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
