# Generated by Django 5.0.6 on 2024-06-03 11:23

from django.db import migrations, models
import datetime


def set_default_completed_at(apps, schema_editor):
    Todo = apps.get_model('todo', 'Todo')
    todos = Todo.objects.filter(completed_at__isnull=True)
    for todo in todos:
        todo.completed_at = datetime.datetime.now()
        todo.save()

class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_alter_todo_completed_at"),
    ]

    operations = [
        migrations.RunPython(set_default_completed_at),
        migrations.RemoveField(
            model_name="todo",
            name="star",
        ),
        migrations.AlterField(
            model_name="todo",
            name="completed_at",
            field=models.DateTimeField(blank=True),
        ),
    ]
