# Generated by Django 5.0.6 on 2024-06-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_alter_todo_completed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="star",
        ),
        migrations.AlterField(
            model_name="todo",
            name="completed_at",
            field=models.DateTimeField(blank=True),
        ),
    ]
