# Generated by Django 5.0.6 on 2024-06-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0004_remove_todo_star_alter_todo_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
