# Generated by Django 5.0.6 on 2024-06-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0005_alter_todo_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="star",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
