# Generated by Django 5.0.6 on 2024-06-04 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0006_todo_star"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="star",
        ),
    ]
