# Generated by Django 5.0.6 on 2024-06-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="blogs", to="category.category"
            ),
        ),
    ]
